services:
    rmcgirr83.requirereason.listener:
        class: rmcgirr83\requirereason\event\listener
        arguments:
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
